import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Cooker",
  description: "Recipes generated by AI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-primary">
      <body className={clsx(inter.className, "h-full")}>{children}</body>
    </html>
  );
}
