import type { Metadata } from "next";
import { Raleway } from "next/font/google";
import "./globals.css";
import clsx from "clsx";

const inter = Raleway({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "AI Cooker",
  description: "Recipes generated by AI",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full bg-primary">
      <body
        className={clsx(inter.className, "min-h-full", "bg-cover bg-fixed")}
        style={{
          backgroundImage: "url('/layout.jpeg')",
        }}
      >
        <div
          className="fixed inset-0 bg-white opacity-75" // Ajustez l'opacité ici (0 pour transparent, 100 pour opaque)
        />
        {children}
      </body>
    </html>
  );
}
